"""
Report Generator for LegacyLink AI
Generates README and modernization reports
"""

from typing import List, Dict, Optional
from datetime import datetime


class ReportGenerator:
    """Generate documentation and modernization reports"""
    
    def generate_readme(self, tables: List[Dict]) -> str:
        """
        Generate README.md for the generated project
        
        Args:
            tables: List of table dictionaries
            
        Returns:
            Complete README.md content
        """
        table_names = [table['clean_name'] for table in tables]
        
        readme = f"""# Generated SQLAlchemy Models

This project was automatically generated by **LegacyLink AI** - an IBM Bob-assisted legacy SQL schema modernization tool.

## 📋 Overview

This package contains modernized SQLAlchemy 2.0 ORM models generated from legacy database schema.

**Generated Models:**
{self._format_list(table_names)}

**Generation Date:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 🚀 Quick Start

### Installation

```bash
pip install -r requirements.txt
```

### Usage

```python
from sqlalchemy import create_engine
from sqlalchemy.orm import Session
from database import Base
from models import {', '.join(table_names[:3])}{'...' if len(table_names) > 3 else ''}

# Create database engine
engine = create_engine('sqlite:///database.db')

# Create all tables
Base.metadata.create_all(engine)

# Use the models
with Session(engine) as session:
    # Example: Create a new record
    # new_record = Customer(first_name="John", last_name="Doe")
    # session.add(new_record)
    # session.commit()
    pass
```

## 📁 Project Structure

```
.
├── models.py                  # SQLAlchemy ORM models
├── database.py                # Database configuration
├── test_models.py             # Pytest test suite
├── README.md                  # This file
├── modernization_report.md   # Detailed transformation report
└── requirements.txt           # Python dependencies
```

## 🧪 Running Tests

```bash
pytest test_models.py -v
```

## 📊 Models Overview

{self._generate_models_overview(tables)}

## 🔧 Customization

These generated models are a starting point. You may want to:

- Add relationships between models using `relationship()`
- Add custom methods and properties
- Implement validation logic
- Add indexes for performance optimization
- Configure cascade behaviors for foreign keys

## 📚 Documentation

- [SQLAlchemy 2.0 Documentation](https://docs.sqlalchemy.org/en/20/)
- [SQLAlchemy ORM Tutorial](https://docs.sqlalchemy.org/en/20/tutorial/)

## ⚠️ Important Notes

- Review all generated models before using in production
- Verify data types match your requirements
- Add appropriate indexes for your query patterns
- Consider adding database migrations using Alembic

## 🤖 Generated by LegacyLink AI

This project was generated using LegacyLink AI, powered by IBM Bob.

For more information, see `modernization_report.md`.
"""
        return readme
    
    def generate_modernization_report(self, tables: List[Dict], transformation_log: List[Dict],
                                     functions: Optional[List[Dict]] = None, indexes: Optional[List[Dict]] = None) -> str:
        """
        Generate detailed modernization report
        
        Args:
            tables: List of table dictionaries
            transformation_log: List of transformation records
            functions: List of function/procedure dictionaries (optional)
            indexes: List of index dictionaries (optional)
            
        Returns:
            Complete modernization_report.md content
        """
        functions = functions or []
        indexes = indexes or []
        
        report = f"""# Modernization Report

**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
**Tool:** LegacyLink AI (IBM Bob-assisted)

## Executive Summary

This report documents the transformation of legacy SQL schema into modern SQLAlchemy 2.0 ORM models.

**Statistics:**
- **Tables Processed:** {len(tables)}
- **Total Columns:** {sum(len(table['columns']) for table in tables)}
- **Functions/Procedures Found:** {len(functions)}
- **Indexes Found:** {len(indexes)}
- **Transformations Applied:** {len(transformation_log)}

## Table Transformations

{self._generate_table_transformations(tables)}

{self._generate_functions_section(functions)}

{self._generate_indexes_section(indexes)}

## Detailed Transformation Log

{self._generate_transformation_details(transformation_log)}

## Type Mappings Applied

The following SQL types were mapped to SQLAlchemy types:

| SQL Type | SQLAlchemy Type | Python Type |
|----------|----------------|-------------|
| INT, INTEGER | Integer | int |
| VARCHAR(n) | String(n) | str |
| TEXT | Text | str |
| TIMESTAMP, DATETIME | DateTime | datetime |
| DATE | Date | datetime |
| BOOLEAN, BOOL | Boolean | bool |
| DECIMAL, NUMERIC | Numeric | float |
| FLOAT, DOUBLE | Float | float |

## Naming Conventions Applied

### Table Names
- Removed prefixes: `tbl_`, `tb_`, `t_`
- Removed version suffixes: `_2012_v2`, `_v1`
- Expanded abbreviations to full words
- Converted to PascalCase for class names
- Pluralized for database table names

### Column Names
- Removed type prefixes: `vch_`, `int_`, `dec_`, `dt_`, `fk_`, `c_`
- Expanded abbreviations to full words
- Converted to snake_case
- Standardized timestamp columns to `*_at` format

## Generated Files

1. **models.py** - SQLAlchemy ORM model classes
2. **database.py** - Base configuration for SQLAlchemy
3. **test_models.py** - Pytest test suite for models
4. **README.md** - Project documentation and usage guide
5. **requirements.txt** - Python package dependencies

## Recommendations

### Immediate Actions
1. Review all generated models for accuracy
2. Run the test suite: `pytest test_models.py`
3. Verify data types match your requirements
4. Add any missing relationships between models

### Future Enhancements
1. Add database migrations using Alembic
2. Implement custom validation logic
3. Add indexes for frequently queried columns
4. Configure cascade behaviors for foreign keys
5. Add business logic methods to model classes

## Quality Assurance

All generated code follows:
- SQLAlchemy 2.0 best practices
- PEP 8 Python style guide
- Type hints for better IDE support
- Comprehensive test coverage

## Support

For issues or questions about the generated code:
1. Review the SQLAlchemy 2.0 documentation
2. Check the test suite for usage examples
3. Consult the README.md for setup instructions

---

**Generated by LegacyLink AI**  
*IBM Bob-assisted legacy SQL schema modernization*
"""
        return report
    
    def generate_requirements(self) -> str:
        """
        Generate requirements.txt
        
        Returns:
            requirements.txt content
        """
        return """sqlalchemy>=2.0.0
pytest>=7.0.0
"""
    
    def _format_list(self, items: List[str]) -> str:
        """Format a list of items as markdown bullet points"""
        return '\n'.join(f'- `{item}`' for item in items)
    
    def _generate_models_overview(self, tables: List[Dict]) -> str:
        """Generate overview section for each model"""
        sections = []
        
        for table in tables:
            class_name = table['clean_name']
            table_name = table['table_name']
            original_name = table['original_name']
            columns = table['columns']
            
            section = f"""### {class_name}

**Table Name:** `{table_name}`  
**Original Name:** `{original_name}`  
**Columns:** {len(columns)}

Key columns:
{self._format_list([col['clean_name'] for col in columns[:5]])}
{'- ...' if len(columns) > 5 else ''}
"""
            sections.append(section)
        
        return '\n'.join(sections)
    
    def _generate_table_transformations(self, tables: List[Dict]) -> str:
        """Generate table transformation details"""
        sections = []
        
        for table in tables:
            section = f"""### {table['original_name']} → {table['clean_name']}

**Original Table:** `{table['original_name']}`  
**Generated Class:** `{table['clean_name']}`  
**Database Table:** `{table['table_name']}`

**Column Transformations:**

| Original Column | Clean Column | Type | Constraints |
|----------------|--------------|------|-------------|
"""
            for col in table['columns']:
                constraints = []
                if col.get('primary_key'):
                    constraints.append('PRIMARY KEY')
                if not col.get('nullable', True):
                    constraints.append('NOT NULL')
                if col['clean_name'].endswith('_id') and not col.get('primary_key'):
                    constraints.append('INDEXED')
                
                constraint_str = ', '.join(constraints) if constraints else '-'
                section += f"| `{col['original_name']}` | `{col['clean_name']}` | {col['type']} | {constraint_str} |\n"
            
            sections.append(section)
        
        return '\n'.join(sections)
    
    def _generate_transformation_details(self, transformation_log: List[Dict]) -> str:
        """Generate detailed transformation log"""
        if not transformation_log:
            return "*No transformations logged*"
        
        # Group by table/column
        table_logs = {}
        column_logs = {}
        
        for log in transformation_log:
            if log['type'] == 'Table':
                original = log['original']
                if original not in table_logs:
                    table_logs[original] = []
                table_logs[original].append(log['change'])
            else:
                original = log['original']
                if original not in column_logs:
                    column_logs[original] = []
                column_logs[original].append(log['change'])
        
        sections = []
        
        if table_logs:
            sections.append("### Table Name Transformations\n")
            for original, changes in table_logs.items():
                sections.append(f"**{original}:**")
                for change in changes:
                    sections.append(f"- {change}")
                sections.append("")
        
        if column_logs:
            sections.append("### Column Name Transformations\n")
            for original, changes in column_logs.items():
                sections.append(f"**{original}:**")
                for change in changes:
                    sections.append(f"- {change}")
                sections.append("")
        
        return '\n'.join(sections)
    
    def _generate_functions_section(self, functions: List[Dict]) -> str:
        """Generate section documenting legacy functions and procedures"""
        if not functions:
            return ""
        
        section = f"""## Legacy Functions and Procedures

**Found {len(functions)} function(s)/procedure(s) in the legacy schema.**

These legacy database functions should be reviewed and potentially refactored into application-level code:

"""
        for func in functions:
            returns_info = ""
            if func.get('returns'):
                returns_preview = func['returns'][:100] + "..." if len(func['returns']) > 100 else func['returns']
                returns_info = f"\n**Returns:** `{returns_preview}`"
            
            section += f"""### {func['name']}

**Type:** {func['type'].title()}  
**Language:** {func['language']}{returns_info}

**Modernization Recommendation:**
- Consider refactoring this logic into Python application code
- Use SQLAlchemy queries instead of database-side logic where possible
- If complex business logic, consider creating a service layer
- For reporting functions, consider using pandas or similar tools

---

"""
        
        return section
    
    def _generate_indexes_section(self, indexes: List[Dict]) -> str:
        """Generate section documenting legacy indexes"""
        if not indexes:
            return ""
        
        section = f"""## Legacy Indexes

**Found {len(indexes)} index(es) in the legacy schema.**

These indexes should be recreated in your SQLAlchemy models for optimal performance:

"""
        for idx in indexes:
            unique_str = "UNIQUE " if idx['unique'] else ""
            section += f"""### {idx['name']}

**Type:** {unique_str}Index  
**Table:** `{idx['table']}`  
**Columns:** `{idx['columns']}`

**Implementation in SQLAlchemy:**
```python
# Add to your {idx['table']} model:
__table_args__ = (
    Index('{idx['name']}', '{idx['columns'].replace(',', "', '")}'{', unique=True' if idx['unique'] else ''}),
)
```

---

"""
        
        return section

# Made with Bob
